spring:
  application:
    name: fraudriskapi

  datasource:
    url: jdbc:postgresql://localhost:5432/fraudrisk
    username: fraudapi
    password: ${DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

ml:
  service:
    base-url: http://localhost:8000

server:
  port: 8082
