spring:
  application:
    name: fraudriskapi

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fraud_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

ml:
  service:
    base-url: http://localhost:8000

server:
  port: 8082
